 export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
 export const GET_LIGHTS = "GET_LIGHTS";
 export const UPDATE_LIGHT = "UPDATE_LIGHT";
 export const NAVIGATION_UPDATE = "NAVIGATION_UPDATE";
 export const ENVIRONMENT_UPDATE = "ENVIRONMENT_UPDATE";
 export const TOGGLE_MENU = "TOGGLE_MENU";